/* ================================================================
   THE WOODER - prompt.js (v2)
   ================================================================
   Construction du prompt envoye a l'API Claude pour l'analyse photo.

   Nouveau v2 : Le prompt demande un champ "composition" qui decrit
   l'agencement de la facade en lignes horizontales. Ca permet aux
   archetypes de reproduire correctement les colonnes mixtes :
   portes en haut + tiroirs en bas, etc.

   Depend de : state.js
   ================================================================ */

function construirePrompt(L, H, P) {
  return [
    'Tu es menuisier fabricant experimente. Analyse cette photo pour identifier chaque element de fabrication separe.',
    '',
    'DIMENSIONS TOTALES CONNUES (donnees par l\'utilisateur, a utiliser en priorite) :',
    '- Largeur totale : ' + L + ' cm',
    '- Hauteur totale : ' + H + ' cm',
    '- Profondeur totale : ' + P + ' cm',
    'Utilise ces valeurs EXACTES pour ensemble.dimensions_totales et repartis les elements dans cet espace.',
    '',
    'NOMENCLATURE :',
    '- COL = Colonne pleine hauteur',
    '- CB = Caisson bas (pose au sol)',
    '- CH = Caisson haut (fixe en hauteur)',
    '- NO = Niche ouverte',
    '- DC = Demi-colonne',
    'Sous-elements : PB=porte battante, PC=porte coulissante, TIR=tiroir, ETG=etagere, PEND=penderie, MI=montant intermediaire, PLI=plinthe.',
    '',
    'REGLES CRITIQUES DE DECOMPOSITION :',
    '',
    '1. MONTANTS VS LIGNES ENTRE PORTES :',
    '   - Une simple ligne verticale fine entre 2 portes dans un meme caisson = ce n\'est PAS un montant, c\'est juste le jeu entre les portes. Mettre MI=0.',
    '   - Un vrai montant intermediaire = un panneau structurel d\'environ 18mm visible, qui divise l\'interieur du caisson en colonnes.',
    '   - Si tu hesites : regarde si les poignees des 2 portes sont proches (= meme caisson, pas de MI) ou tres eloignees (= possible montant).',
    '',
    '2. JOUES CONTINUES :',
    '   - Si les joues laterales montent du bas en haut sans coupure = 1 SEUL element, meme avec plusieurs portes empilees.',
    '   - Si tu vois une ligne horizontale qui separe clairement 2 meubles = 2 elements separes.',
    '',
    '3. COLONNES COTE A COTE :',
    '   - 2 colonnes independantes avec joues doublees entre elles = 2 elements COL separes.',
    '   - Si ambigu, prefere scinder en plusieurs elements independants.',
    '',
    '4. COMPTAGE PRECIS :',
    '   - Pour CHAQUE element, compter EXACTEMENT toutes les portes visibles (haut + bas si empilees).',
    '   - Compter TOUS les tiroirs visibles, meme petits.',
    '   - Un caisson avec 2 portes en haut et 2 tiroirs en bas : PB=2 ET TIR=2.',
    '   - Ne jamais oublier les tiroirs en partie basse d\'une colonne.',
    '',
    '5. NICHES OUVERTES :',
    '   - Une niche ouverte dans un materiau different = TOUJOURS un element NO separe.',
    '   - Compter precisement les etageres visibles dans la niche.',
    '',
    '6. PORTES ET PLINTHE : EN APPLIQUE par defaut.',
    '',
    '7. MURS BLANCS : ne pas confondre un mur blanc avec un montant de meuble.',
    '',
    'COMPOSITION DE LA FACADE (CRUCIAL POUR LA FABRICATION) :',
    'Pour chaque element, decris l\'agencement de la facade en "lignes horizontales" de haut en bas.',
    'Chaque ligne a :',
    '  - ligne : numero (1 = en haut, 2 = en dessous, etc.)',
    '  - hauteur_ratio : proportion de la hauteur totale du meuble (la somme des ratios doit faire 1.0)',
    '                    OU null si tu n\'arrives pas a estimer precisement (ombre, angle difficile...)',
    '  - elements : liste d\'elements de gauche a droite, type = "porte" | "tiroir" | "ouvert" | "vitree"',
    '',
    'EXEMPLES :',
    '',
    'Cas 1 - Colonne 2 portes pleine hauteur cote a cote :',
    '  "composition":[{"ligne":1,"hauteur_ratio":1.0,"elements":[{"type":"porte"},{"type":"porte"}]}]',
    '',
    'Cas 2 - Colonne mixte : 2 portes en haut + 2 tiroirs en bas (cas tres frequent) :',
    '  "composition":[',
    '    {"ligne":1,"hauteur_ratio":0.7,"elements":[{"type":"porte"},{"type":"porte"}]},',
    '    {"ligne":2,"hauteur_ratio":0.3,"elements":[{"type":"tiroir"},{"type":"tiroir"}]}',
    '  ]',
    '',
    'Cas 3 - Caisson bas 3 tiroirs progressifs (petit en haut, grand en bas) :',
    '  "composition":[',
    '    {"ligne":1,"hauteur_ratio":0.2,"elements":[{"type":"tiroir"}]},',
    '    {"ligne":2,"hauteur_ratio":0.35,"elements":[{"type":"tiroir"}]},',
    '    {"ligne":3,"hauteur_ratio":0.45,"elements":[{"type":"tiroir"}]}',
    '  ]',
    '',
    'Cas 4 - Colonne 2 portes empilees (une grande porte haute + une courte basse) :',
    '  "composition":[',
    '    {"ligne":1,"hauteur_ratio":0.6,"elements":[{"type":"porte"}]},',
    '    {"ligne":2,"hauteur_ratio":0.4,"elements":[{"type":"porte"}]}',
    '  ]',
    '',
    'Cas 5 - Niche ouverte pleine hauteur :',
    '  "composition":[{"ligne":1,"hauteur_ratio":1.0,"elements":[{"type":"ouvert"}]}]',
    '',
    'SI TU N\'ES PAS SUR des proportions, mets hauteur_ratio a null. Mieux vaut etre honnete que de donner des ratios faux.',
    '',
    'METHODE D\'ANALYSE :',
    'a) Scanner de GAUCHE a DROITE',
    'b) Pour chaque colonne/zone, scanner de BAS en HAUT',
    'c) Pour chaque element : compter exactement portes haut, portes bas, tiroirs',
    'd) Construire la composition en lignes horizontales',
    'e) Materiau different = element separe',
    '',
    'Reponds UNIQUEMENT en JSON :',
    '{"ensemble":{"nom_client":"","nom_technique":"","style":"","materiau_apparent":"","dimensions_totales":{"hauteur":' + H + ',"largeur":' + L + ',"profondeur":' + P + '},"particularites":[]},"elements":[{"id":"","nom_client":"","nom_technique":"","type":"","zone_horizontale":"","largeur":0,"hauteur":0,"profondeur":0,"facade":{"type":"","nb_portes":0,"nb_tiroirs":0,"nb_etg":0,"detail_portes":"","pose":"applique","composition":[]},"sous_elements":{"MI":0,"PB":0,"PC":0,"TIR":0,"ETG":0,"PEND":0,"PLI":"applique"}}]}'
  ].join('\n');
}
