/* ================================================================
   THE WOODER - prompt.js (v3)
   ================================================================
   CHANGELOG v3 :
   - Ajout de la description des sous_colonnes pour les meubles
     avec montants intermediaires (MI > 0)
   - Regles renforcees sur MI : pas de MI si tiroirs, pas de MI
     si seulement une fine ligne entre 2 portes
   ================================================================ */

function construirePrompt(L, H, P) {
  return [
    'Tu es menuisier fabricant experimente. Analyse cette photo pour identifier chaque element de fabrication separe.',
    '',
    'DIMENSIONS TOTALES CONNUES (donnees par l\'utilisateur, a utiliser en priorite) :',
    '- Largeur totale : ' + L + ' cm',
    '- Hauteur totale : ' + H + ' cm',
    '- Profondeur totale : ' + P + ' cm',
    'Utilise ces valeurs EXACTES pour ensemble.dimensions_totales et repartis les elements dans cet espace.',
    '',
    'NOMENCLATURE :',
    '- COL = Colonne pleine hauteur',
    '- CB = Caisson bas (pose au sol)',
    '- CH = Caisson haut (fixe en hauteur)',
    '- NO = Niche ouverte',
    '- DC = Demi-colonne',
    'Sous-elements : PB=porte battante, PC=porte coulissante, TIR=tiroir, ETG=etagere, PEND=penderie, MI=montant intermediaire, PLI=plinthe.',
    '',
    'REGLES CRITIQUES :',
    '',
    '1. MONTANTS INTERMEDIAIRES (MI) :',
    '   - Un VRAI montant intermediaire = un panneau vertical STRUCTUREL d\'epaisseur visible (~18mm) qui divise l\'INTERIEUR du caisson en sous-colonnes.',
    '   - Une simple ligne fine entre 2 portes = juste le JEU entre portes. Pas un MI. Mettre MI=0.',
    '   - TIROIRS + MI IMPOSSIBLE : si tu vois des tiroirs dans un caisson, il ne peut pas y avoir de montant intermediaire (les tiroirs Tandem occupent toute la largeur). Dans ce cas, force MI=0.',
    '   - Indice fiable : si le meuble est tres large (>1600mm) avec plusieurs portes reparties, il y a probablement un MI. Si meuble etroit (<1000mm), probablement pas.',
    '',
    '2. JOUES CONTINUES :',
    '   - Si les joues laterales montent de bas en haut sans coupure = 1 SEUL element, meme avec plusieurs portes.',
    '',
    '3. ANGLES : Un angle = TOUJOURS des meubles separes.',
    '',
    '4. COMPTAGE PRECIS :',
    '   - Pour CHAQUE element, compter EXACTEMENT toutes les portes visibles.',
    '   - Compter TOUS les tiroirs visibles, meme petits.',
    '   - Ne pas oublier les tiroirs en partie basse d\'une colonne.',
    '',
    '5. NICHES : Une niche dans un materiau different = element NO separe.',
    '',
    '6. PORTES ET PLINTHE : EN APPLIQUE par defaut.',
    '',
    '7. MURS BLANCS : ne pas confondre un mur avec un montant.',
    '',
    'COMPOSITION DE LA FACADE (CRUCIAL) :',
    'Pour chaque element, decris l\'agencement en "lignes horizontales" de haut en bas.',
    'Chaque ligne a :',
    '  - ligne : numero (1 en haut, 2 en dessous, etc.)',
    '  - hauteur_ratio : proportion de la hauteur totale (somme des ratios = 1.0) OU null si non estimable',
    '  - elements : liste d\'elements de gauche a droite, type = "porte" | "tiroir" | "ouvert" | "vitree"',
    '',
    'SI MI > 0 : chaque ligne doit aussi avoir un champ "sous_colonnes" qui decrit comment les elements sont repartis entre les sous-colonnes.',
    '  Chaque sous-colonne a :',
    '  - largeur_ratio : proportion de la largeur totale du meuble (somme = 1.0)',
    '  - elements : liste d\'elements dans cette sous-colonne, de haut en bas',
    '',
    'EXEMPLES :',
    '',
    'Cas 1 - Colonne simple 2 portes pleine hauteur :',
    '  "composition":[{"ligne":1,"hauteur_ratio":1.0,"elements":[{"type":"porte"},{"type":"porte"}]}]',
    '',
    'Cas 2 - Colonne mixte : 2 portes haut + 2 tiroirs bas (MI = 0, tiroirs presents) :',
    '  "composition":[',
    '    {"ligne":1,"hauteur_ratio":0.7,"elements":[{"type":"porte"},{"type":"porte"}]},',
    '    {"ligne":2,"hauteur_ratio":0.3,"elements":[{"type":"tiroir"},{"type":"tiroir"}]}',
    '  ]',
    '',
    'Cas 3 - Armoire large avec 1 MI : 2 portes a gauche + 1 porte a droite :',
    '  MI=1, PB=3',
    '  "composition":[{',
    '    "ligne":1, "hauteur_ratio":1.0,',
    '    "elements":[{"type":"porte"},{"type":"porte"},{"type":"porte"}],',
    '    "sous_colonnes":[',
    '      {"largeur_ratio":0.6, "elements":[{"type":"porte"},{"type":"porte"}]},',
    '      {"largeur_ratio":0.4, "elements":[{"type":"porte"}]}',
    '    ]',
    '  }]',
    '',
    'Cas 4 - Armoire avec 1 MI, 2 portes symetriques (1 de chaque cote) :',
    '  MI=1, PB=2',
    '  "composition":[{',
    '    "ligne":1, "hauteur_ratio":1.0,',
    '    "elements":[{"type":"porte"},{"type":"porte"}],',
    '    "sous_colonnes":[',
    '      {"largeur_ratio":0.5, "elements":[{"type":"porte"}]},',
    '      {"largeur_ratio":0.5, "elements":[{"type":"porte"}]}',
    '    ]',
    '  }]',
    '',
    'Cas 5 - Niche ouverte pleine hauteur :',
    '  "composition":[{"ligne":1,"hauteur_ratio":1.0,"elements":[{"type":"ouvert"}]}]',
    '',
    'SI TU N\'ES PAS SUR des proportions, mets null. Mieux vaut etre honnete.',
    '',
    'METHODE :',
    'a) Scanner GAUCHE a DROITE',
    'b) Pour chaque zone, BAS en HAUT',
    'c) Compter portes / tiroirs precisement',
    'd) Si tiroirs presents : MI=0',
    'e) Si MI>0 : decrire les sous_colonnes dans la composition',
    '',
    'Reponds UNIQUEMENT en JSON :',
    '{"ensemble":{"nom_client":"","nom_technique":"","style":"","materiau_apparent":"","dimensions_totales":{"hauteur":' + H + ',"largeur":' + L + ',"profondeur":' + P + '},"particularites":[]},"elements":[{"id":"","nom_client":"","nom_technique":"","type":"","zone_horizontale":"","largeur":0,"hauteur":0,"profondeur":0,"facade":{"type":"","nb_portes":0,"nb_tiroirs":0,"nb_etg":0,"detail_portes":"","pose":"applique","composition":[]},"sous_elements":{"MI":0,"PB":0,"PC":0,"TIR":0,"ETG":0,"PEND":0,"PLI":"applique"}}]}'
  ].join('\n');
}
